#!/usr/bin/env bash

echo -e "Installing nodejs"

echo -e "\tSetting up asdf"
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git >/dev/null 2>&1
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring >/dev/null 2>&1

# Set the containing directory for later use
versions_dir="${HOME}/.dotfiles/installer/versions/nodejs"

# Read given file line by line
function read_file {
  local file_path="${versions_dir}"
  while read -r line
  do
    echo -e "${line}"
  done < "${file_path}"
}

# Install list of versions one by one
function install_versions {
  local versions_list=$(read_file)
  for version in ${versions_list}; do
    echo -e "\t\tInstalling ${version}"
    asdf install nodejs ${version} > nodejs.install.log
    local status=$?
    if [ ${status} -ne "0" ]; then
      echo "Last exit code was ${status} for 'asdf install nodejs ${version}'. Please run manually. Aborting."
      exit 1
    fi
  done
  # Set the latest version as global
  set_global ${version}
}

function set_global {
  local latest_version=${1}
  echo -e "\tSetting ${latest_version} as global"
  asdf global nodejs ${latest_version} >/dev/null 2>&1
}

echo -e "\tInstalling versions"
install_versions 

echo -e "\tInstalling yarn"
npm install -g yarn >/dev/null 2>&1

# Typescript
echo -e "\tInstalling typescript"
npm install -g typescript >/dev/null 2>&1

echo -e "\tInstalling neovim bindings"
npm install -g neovim >/dev/null 2>&1
