#!/usr/bin/env bash

alias nvim-lazy="NVIM_APPNAME=LazyVim nvim"
alias nvim-lazy="NVIM_APPNAME=FoShizzle nvim"

function nvims() {
  items=("default" "FoShizzle")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim "$@"
}

