#!/usr/bin/env bash

dot_dir="${HOME}/.dotfiles"

echo -e "Updating macOS"
sudo softwareupdate -i -a

echo -e "Updating brew"
brew update >/dev/null 2>&1

echo -e "\tUpgrading brew installs"
brew upgrade

echo -e "\tUpgrading brew cask installs"
brew upgrade --cask

echo -e "Updating neovim"
# nvim +PlugUpdate +qall
# nvim +CocUpdateSync +qall
nvim +PackerUpdate +qall

echo -e "Updating asdf"
asdf plugin-update --all
