#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo -e "Updating Homebrew"
brew update >/dev/null

# Set the containing directory for later use
tools_dir="${HOME}/.dotfiles/installer/tools"

# Read given file line by line
function read_file {
  local file_path="${tools_dir}/${1}"
  while read -r line
  do
    echo -e "${line}"
  done < "${file_path}"
}

# Install list of tools one by one
function install_tools {
  local file_name=${1}
  local tool_list=$(read_file ${file_name})
  for tool in ${tool_list}; do
    echo -e "\t\tInstalling ${tool}"
    brew_install ${tool}
  done
}

function brew_install {
  local program_name=$@
  brew install ${program_name} >/dev/null 2>&1
  local status=$?
  if [ ${status} -ne "0" ]; then
    echo "Last exit code was ${status} for 'brew install ${program_name}'. Please run manually. Aborting."
    exit 1
  fi
}

###############################################################################
# System tool an macOS version replacements                                   #
###############################################################################

echo -e "Installing system tools via Homebrew"

# Install GNU core utilities (those that com with macOS are outdated).
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin)` to `${PATH}`.
# Install some other useful utilities like `sponge`.
# Install GNU `find`, `locate`, `updatedb` and `xargs`. `g`-prefixed.
# Install GNU `sed`, overwriting the built-in one
echo -e "\tInstalling core utilities"
install_tools "core"
sudo ln -nfs /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

echo -e "\tInstalling basic web tools"
install_tools "web"

echo -e "\tInstalling useful helpers"
install_tools "helpers"

###############################################################################
# Development tools                                                           #
###############################################################################

echo -e "Installing common development tools via Homebrew"

echo -e "\tInstalling terminal tools"
install_tools "terminal"

echo -e "\tInstalling development tools"
install_tools "development"

echo -e "\tInstalling documentation tools"
install_tools "documentation"

echo -e "\tInstalling additional common build tools"
install_tools "build"

echo -e "\tInstalling asdf version manager"
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8 >/dev/null 2>&1

echo -e "\tCleaning up"
brew cleanup >/dev/null 2>&1
