#!/usr/bin/env bash

set -eu
set -o pipefail
shopt -s nullglob

self=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
dotfiles="${HOME}/.dotfiles"

function check_or_install_brew {
  echo -e "Checking Xcode CLI tools"
  xcode-select --install >/dev/null 2>&1 || echo "Xcode CLI tools are installed"

  # Install brew
  echo -e "Checking Homebrew installation"
  command -v brew >/dev/null 2>&1 && echo -e "Homebrew is installed" || {
    echo -e >&2 "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  }

  echo -e "Updating Homebrew installation"
  brew update
}

function install {
  source "${self}/helpers/sudo"
  echo -e "Installing or updating tools and apps via Homebrew..."
  brew bundle install --file ${dotfiles}/Brewfile

}

check_or_install_brew
install

cat << EOF 

******************************************************************************
* Note that you need to setup and add licenses to the installed apps.        *
******************************************************************************

EOF

