#!/usr/bin/env bash

echo -e "Installing neovim"

echo -e "\tSetting up asdf"
asdf plugin-add neovim >/dev/null 2>&1
brew install cmake >/dev/null 2>&1

# Set the containing directory for later use
versions_dir="${HOME}/.dotfiles/installer/versions/neovim"

# Read given file line by line
function read_file {
  local file_path="${versions_dir}"
  while read -r line
  do
    echo -e "${line}"
  done < "${file_path}"
}

# Install list of versions one by one
function install_versions {
  local versions_list=$(read_file)
  for version in ${versions_list}; do
    echo -e "\t\tInstalling ${version}"
    asdf install ruby ${version} >/dev/null 2>&1
    local status=$?
    if [ ${status} -ne "0" ]; then
      echo "Last exit code was ${status} for 'asdf install neovim ${version}'. Please run manually. Aborting."
      exit 1
    fi
  done
  # Set the latest version as global
  set_global ${version}
}

function set_global {
  local latest_version=${1}
  echo -e "\tSetting ${latest_version} as global"
  asdf global ruby ${latest_version} >/dev/null 2>&1
}

echo -e "\tInstalling versions"
install_versions 
echo -e "\tInstalling plugins"
nvim +PackerSync +qall -c "q"
