#!/usr/bin/env bash

echo -e "Installing php"

echo -e "\tSetting up asdf"
asdf plugin-add php https://github.com/asdf-community/asdf-php.git >/dev/null 2>&1
echo -e "\t\tInstalling prerequisites"
brew install autoconf automake bison freetype gd gettext icu4c krb5 libedit libiconv libjpeg libpng libxml2 libzip openssl@1.1 pkg-config re2c zlib postgres >/dev/null 2>&1
export PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig:$(brew --prefix krb5)/lib/pkgconfig:$(brew --prefix libedit)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig
export PATH=$(brew --prefix bison)/bin:${PATH}

# Set the containing directory for later use
versions_dir="${HOME}/.dotfiles/installer/versions/php"

# Read given file line by line
function read_file {
  local file_path="${versions_dir}"
  while read -r line
  do
    echo -e "${line}"
  done < "${file_path}"
}

# Install list of versions one by one
function install_versions {
  local versions_list=$(read_file)
  for version in ${versions_list}; do
    echo -e "\t\tInstalling ${version}"
    asdf install php ${version} >/dev/null 2>&1
    local status=$?
    if [ ${status} -ne "0" ]; then
      echo "Last exit code was ${status} for 'asdf install php ${version}'. Please run manually. Aborting."
      exit 1
    fi
  done
  # Set the latest version as global
  set_global ${version}
}

function set_global {
  local latest_version=${1}
  echo -e "\tSetting ${latest_version} as global"
  asdf global php ${latest_version} >/dev/null 2>&1
}

echo -e "\tInstalling versions"
install_versions 

