#!/usr/bin/env bash

set -euo pipefail

plugins_dir="$HOME/.tmux/plugins"
tpm_dir="$plugins_dir/tpm"
mkdir -p "$plugins_dir"

if [[ ! -d $tpm_dir/.git ]]; then
  git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
fi

"$tpm_dir/bin/install_plugins"
