#!/usr/bin/env bash

echo -e "Configuring Vim"
echo -e "\tInstalling neovim plugins"
nvim +PlugInstall +qall -c "q"
#echo -e "\tInstalling Vim plugins"
#vim +PlugInstall +qall -c "q"

# Install extensions
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
if [ ! -f package.json ]
then
  echo '{"dependencies":{}}'> package.json
fi
echo -e "\t\tInstalling coc plugins"
# Change extension names to the extensions you need
npm install \
  --global-style \
  --ignore-scripts \
  --no-bin-links \
  --no-package-lock \
  --only=prod \
  coc-snippets \
  coc-xml \
  coc-json \
  coc-html \
  coc-css \
  coc-prettier \
  coc-tsserver \
  coc-tslint-plugin \
  coc-eslint \
  coc-elixir \
  coc-flutter \
  coc-java \
  coc-phpls >/dev/null 2>&1
