#!/usr/bin/env bash

echo -e "Installing additional zsh tools"

if [ ! -f "${HOME}/.zshrc" ]; then
  echo -e "\tBuilding RC file"
  cat <<-"EOF" > ${HOME}/.zshrc
dot_dir="${HOME}/.dotfiles"
_functions="${dot_dir}/functions"
_exports="${dot_dir}/exports"
_aliases="${dot_dir}/aliases"
_aliases_macos="${dot_dir}/aliases_macos"
_aliases_personal="${dot_dir}/aliases_personal"
_fzf="${dot_dir}/fzf"
_zsh="${dot_dir}/zsh"
_nvims="${dot_dir}/nvims"

for file in \
  ${_functions} \
  ${_exports} \
  ${_aliases} \
  ${_aliases_macos} \
  ${_aliases_personal} \
  ${_fzf} \
  ${_zsh} \
  ${_nvims} ; do
  if [ -f "${file}" ]; then
    source ${file}
  fi
done
EOF
fi

cat << EOF
  
******************************************************************************
* You need to relaunch to shell session: 'exec $SHELL -l'.                   *
* Also likely when running this on a fresh macOS install you need to fix     *
* permissions for autocomplete: 'compautit | xargs chmod g-w,o-w'            *
******************************************************************************

EOF
